# .github/labler.yml
---
# Add 'Multicast' label to any root file changes
Multicast:
  - changed-files:
    - any-glob-to-any-file:
      - 'setup.*'
      - multicast/*.py
      - LICENSE
      - LICENSE.md
      - Logo.svg
      - pyproject.toml

# Add 'Lint' label to any lint file changes
Linter:
  - changed-files:
    - any-glob-to-any-file:
      - '.ast-grep/**/*.yml'
      - .yamllint.conf
      - .bandit.yml
      - .flake8.ini
      - .coveragerc
      - .deepsource.toml
      - .markdownlint.yml
      - tests/check_s*
      - tests/check_c*
      - tests/check_pip

# Add 'bash lang' label to any bash file changes
Bash Lang:
  - changed-files:
    - any-glob-to-any-file:
      - tests/*.bash
      - tests/check_*
      - .github/*.bash
      - .github/*.sh
      - .github/**/*.bash
      - .github/**/*.sh
      - .circleci/*.bash
      - '*.bash'

# Add 'Lang' label to any python file changes
Python Lang:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.py'
      - '*.py'

# Add 'Lang' label to any python file changes
Make Lang:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.makefile'
      - '**/*.make'
      - '**/makefile'
      - Makefile

Configs:
  - changed-files:
    - any-glob-to-any-file:
      - '*.yml'
      - '*.yaml'
      - './**/*.yml'
      - './.**/*.yml'
      - '*.ini'
      - '*.toml'
      - '*.cfg'
      - '*.conf'
      - requirements.txt
      - test-requirements.txt
      - tests/requirements.txt
      - docs/requirements.txt

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '*.md'
      - './**/*.md'
      - docs/**/*
      - docs/*
      - README.md

# Add 'test' label
Testing:
  - changed-files:
    - any-glob-to-any-file:
      - tests/*.py
      - tests/requirements.txt
      - tests/check_*
      - .github/tools/*
      - .github/workflows/*.yml
      - .circleci/*

CI:
  - changed-files:
    - any-glob-to-any-file:
      - tests/*.py
      - tests/requirements.txt
      - .travis.yml
      - .appveyor.yml
      - .github/actions/*/action.yml
      - .github/workflows/*
      - .circleci/*

GitHub:
  - changed-files:
    - any-glob-to-any-file:
      - .github/**/*
      - .github/*
      - README.md

invalid:
  - changed-files:
    - any-glob-to-any-file:
      - .stickler.yml
      - .hound.yml
