[build-system]
requires = ["setuptools>=40.8.0", "build>=1.1.1", "wheel>=0.37"]
build-backend = "setuptools.build_meta"

[pytest.enabler.flake8]
addopts = "--flake8"

[pytest.enabler.doctest]
addopts = "--doctest-glob=**/*.py --doctest-modules"

[pytest.enabler.cov]
addopts = "--cov=. --cov-append --cov-report=xml --junitxml=test-reports/junit.xml"
