version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10
      - image: cimg/python:3.11
      - image: cimg/python:3.12
    resource_class: medium
    environment:
      CI: cicleci
      DEBIAN_FRONTEND: noninteractive
      LANG: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
      SHELL: /bin/bash
    working_directory: ~/multicast
    steps:
      - checkout
      - run:
          name: "fetch and pull"
          command: |
            git fetch && git pull --all || : ;
      - run:
          shell: /bin/bash
          name: "install depends attempt"
          command: |
            python3 -m pip install --user -r ./requirements.txt || : ;
          when: on_success
      - run:
          shell: /bin/bash
          name: "install test depends attempt"
          command: |
            python3 -m pip install --upgrade --user -r ./tests/requirements.txt || : ;
          when: on_success
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/multicast

  test:
    docker:
      - image: cimg/python:3.10
      - image: cimg/python:3.11
      - image: cimg/python:3.12
    parallelism: 2
    resource_class: medium
    environment:
      CI: cicleci
      DEBIAN_FRONTEND: noninteractive
      LANG: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
      SHELL: /bin/bash
    working_directory: ~/multicast
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          shell: /bin/bash
          name: "Installing deps for test"
          command: |
            python3 -m pip install --upgrade --user -r ./tests/requirements.txt || : ;
          when: on_success
      - run:
          shell: /bin/bash
          name: "clean up for test"
          command: |
            make clean
          when: always
      - run:
          shell: /bin/bash
          name: "Unit Tests"
          command: |
            make test
          when: on_success
      - run:
          shell: /bin/bash
          name: "clean up from test"
          command: |
            make clean
          when: always
      - run:
          shell: /bin/bash
          name: "clean up from FAIL"
          command: |
            make clean
          when: on_fail

  pytest:
    docker:
      - image: cimg/python:3.10
      - image: cimg/python:3.11
      - image: cimg/python:3.12
    parallelism: 2
    resource_class: medium
    environment:
      CI: cicleci
      DEBIAN_FRONTEND: noninteractive
      LANG: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
      SHELL: /bin/bash
      # DOCS_BUILD_REF: {{ .Environment.CIRCLE_SHA1 }}
    working_directory: ~/multicast
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          shell: /bin/bash
          name: "set up depends"
          command: |
            python3 -m pip install --upgrade --user -r ./requirements.txt || : ;
          when: on_success
      - run:
          shell: /bin/bash
          name: "clean up for test"
          command: |
            python3 -m pip install --upgrade --user -r ./tests/requirements.txt || : ;
          when: on_success
      - run:
          shell: /bin/bash
          name: "clean up for pytest"
          command: |
            make clean
          when: always
      - run:
          shell: /bin/bash
          name: "pytest Unit Tests"
          command: |
            make test-pytest
          when: on_success
      - store_test_results:
          path: test-reports
          when: on_success
      - store_artifacts:
          path: test-reports
          when: on_success
      - run:
          shell: /bin/bash
          name: "clean up from pytest"
          command: |
            make clean
          when: always
      - run:
          shell: /bin/bash
          name: "clean up from FAIL"
          command: |
            make clean
          when: on_fail

  lint:
    docker:
      - image: cimg/python:3.11
    resource_class: medium
    environment:
      CI: cicleci
      DEBIAN_FRONTEND: noninteractive
      LANG: en_US.UTF-8
      SHELL: /bin/bash
      LC_CTYPE: en_US.UTF-8
    working_directory: ~/multicast
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: "install reqs attempt"
          command: |
            python3 -m pip install --user -r ./requirements.txt || : ;
      - run:
          name: "install test-reqs attempt"
          command: |
            python3 -m pip install --user -r ./tests/requirements.txt || : ;
      - run:
          shell: /bin/bash
          name: "clean up for test"
          command: |
            make clean
      - run:
          shell: /bin/bash
          name: "check code style and spelling"
          command: |
            make test-style || python3 -m flake8 --ignore=W191,W391,E117 --max-line-length=100 --verbose --count --config=.flake8.ini --max-complexity=10
      - run:
          shell: /bin/bash
          name: "clean up when done"
          command: |
            make clean

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - pytest:
          requires:
            - build
            - test
