# .github/workflows/makefile-lint.yml
---
name: Makefile Lint
on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main", "master", "stable"]
  pull_request:
    branches: ["main", "master", "stable", "feature-*", "patch-*", "HOTFIX-*"]

permissions: {}  # Setting default permissions to none for enhanced security

jobs:
  makefile-lint:
    permissions:
      contents: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@4
        with:
          persist-credentials: false
      - name: Install Apt-Get Dependencies
        run: |
          sudo apt-get update || exit 1
          sudo apt-get install -y yamllint golang-go pandoc || exit 1
          go version || { printf "::error file=.github/workflow/makefile-lint.yml,line=25,endLine=27,title=FAILURE::ERROR %s\n" "Go installation failed."; exit 1; }
      - name: Lint Workflow YAML
        if: ${{ success() }}
        run: |
          yamllint -f github --no-warnings .github/workflows/makefile-lint.yml
      - uses: actions/checkout@v4
      - name: Install checkmake
        if: ${{ success() }}
        env:
          BUILDER_NAME: "makefile-lint"
          BUILDER_EMAIL: "no-reply@localhost"
        run: |
          git clone --depth 1 --branch v0.2.2 https://github.com/mrtazz/checkmake.git checkmake
          cd checkmake
          EXPECTED_SHA="48ab7819837d1bdfcbac58e301478a06efebf4a8" # v0.2.2
          ACTUAL_SHA=$(git rev-parse HEAD)
          if [ "$EXPECTED_SHA" != "$ACTUAL_SHA" ]; then
            { printf "::error file=.github/workflow/makefile-lint.yml,line=39,endLine=44,title=FAILURE::ERROR %s\n" "Checkmake repository hash verification failed." ; exit 1; }
          fi
          make || { printf "::error file=.github/workflow/makefile-lint.yml,line=46,endLine=46,title=FAILURE::ERROR %s\n" "Checkmake build failed."; exit 1; }
          cd ..
      - name: Get makefiles Files
        id: makefiles
        shell: bash
        run: |
          FILES=$(git ls-files --exclude-standard -- Makefile 2>/dev/null)
          if [ -z "$FILES" ]; then
            printf "%s\n" "No Makefiles found."
            printf "%s\n" "files=" >> "$GITHUB_OUTPUT"
          else
            printf "%s\n" "Makefiles found:"
            printf "%s\n" "$FILES"
            # Replace line breaks with spaces for GitHub Action Output
            FILES="${FILES//$'\n'/ }"
            printf "%s\n" "files=$FILES" >> "$GITHUB_OUTPUT"
          fi
        if: ${{ success() }}
      - name: Lint Makefiles Files
        run: |
          TOOL_PATH=".github/tool_checkmake.sh"
          if [ ! -x "$TOOL_PATH" ]; then
            printf "::error file=.github/workflow/makefile-lint.yml,line=66,endLine=70,title=FAILURE::ERROR %s\n" "$TOOL_PATH not found or not executable."
            exit 1
          fi
          FILE="${{ steps.makefiles.outputs.files }}" ;
          printf "::group::%s\n" "${FILE}" ;
          "$TOOL_PATH" "${FILE}" || { printf "::error file=.github/workflow/makefile-lint.yml,line=73,endLine=73,title=FAILURE::ERROR %s\n" "Linting failed."; exit 1; } ;
          printf "::endgroup::\n" ; unset FILE 2>/dev/null || true ;
        if: ${{ !cancelled() && steps.makefiles.outputs.files != '' }}
