# .github/workflows/markdown-lint.yml
---
name: Markdown Lint
on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main", "master", "stable"]
  pull_request:
    branches: ["main", "master", "stable", "feature-*", "patch-*", "HOTFIX-*"]

permissions: {}  # Setting default permissions to none for enhanced security

jobs:
  markdown-lint:
    permissions:
      contents: read
      statuses: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Apt-Get Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint npm
          ERR_MSG_STUB="yamllint installation failed."
          ERR_DETAILS="file=.github/workflows/markdown-lint.yml,line=26,endLine=31,title=FAILURE"
          ERR_MSG_LINE="::error ${ERR_DETAILS}::ERROR ${ERR_MSG_STUB}"
          yamllint --version || { printf "%s\n" "${ERR_MSG_LINE}"; exit 1; }

      - name: Lint Workflow YAML
        if: ${{ success() }}
        run: |
          case "${{ vars.YAML_ARGS }}" in
            *[!a-zA-Z0-9\ \-\.]*)
              ERR_MSG_STUB="Invalid YAML_ARGS: contains unauthorized characters"
              ERR_DETAILS="file=.github/workflows/markdown-lint.yml,line=37,endLine=43,"
              ERR_TITLE="title=VALIDATION_ERROR"
              printf "::error %s::ERROR %s\n" "${ERR_DETAILS}${ERR_TITLE}" "${ERR_MSG_STUB}"
              exit 1
              ;;
            *)
              printf "Validating workflow with args: %s\n" "${YAML_ARGS}"
              yamllint ${YAML_ARGS} .github/workflows/markdown-lint.yml
              ;;
          esac

      - name: Install NPM Dependencies
        run: |
          sudo npm install -g markdownlint
          sudo npm install -g markdownlint-cli

      - name: Lint YAML config for markdown
        run: |
          yamllint -f github --no-warnings .markdownlint.yaml

      - name: Lint Markdown Files with YAML config
        if: ${{ !cancelled() }}
        run: |
          git ls-files --exclude-standard -z -- *.md **/*.md |\
          xargs -0 -I{} markdownlint "{}" --config .markdownlint.yaml ;

      - name: Lint Markdown Files with JSON config
        if: ${{ !cancelled() }}
        run: |
          git ls-files --exclude-standard -z -- *.md **/*.md |\
          xargs -0 -I{} markdownlint "{}" --config .markdownlint.json ;
