name: CI
on: [push]
jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Pre-Clean
      id: clean
      run: make -j1 -f Makefile clean || true ;
    - name: Test Build
      id: build
      run: make -j1 -f Makefile build || true ;
    - name: Post-Clean
      id: post
      run: make -j1 -f Makefile purge || true ;

  MATS:
    if: ${{ always() }}
    needs: BUILD
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup dependencies
      run: |
        pip install -r ./requirements.txt ;
        pip install coverage || true ;
    - name: Pre-Clean
      id: pre
      run: make -j1 -f Makefile clean || true ;
    - name: Run Tests
      id: tests
      run: make -j1 -f Makefile test ;
    - name: Post-Clean
      id: post
      run: make -j1 -f Makefile clean || true ;
      if: ${{ always() }}

  COVERAGE:
    if: ${{ success() }}
    needs: [BUILD, MATS]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    env:
      OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@master
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies for ${{ matrix.python-version }}
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r ./requirements.txt ;
        pip install coverage ;
    - name: Pre-Clean
      run: make -j1 -f Makefile clean || true ;
    - name: Generate Coverage
      run: |
        make -f Makefile test ; wait ;
        python -m coverage xml || coverage xml || true ;
    - name: Upload Python ${{ matrix.python-version }} coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        env_vars: OS,PYTHON_VERSION
        fail_ci_if_error: true
        flags: unittests
        name: "codecov-github-action"
        verbose: true
        directory: .
    - name: Post-Clean
      run: make -j1 -f Makefile clean || true ;
      if: ${{ always() }}


  STYLE:
    if: ${{ always() }}
    needs: [BUILD, MATS]
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: '3.9'

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Setup Linters
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r ./requirements.txt ;
        pip install flake8 ;
        pip install pyflakes ;
        pip install pep8 ;
    - name: Pre-Clean
      run: make -j1 -f Makefile clean || true ;
    - name: Testing Style
      run: make -j1 -f Makefile test-style ;
    - name: Post-Clean
      run: make -j1 -f Makefile clean || true ;
      if: ${{ always() }}

  TOX:
    needs: [MATS, STYLE, COVERAGE]
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: '3.9'

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: install TOX
      run: |
        python -m pip install --upgrade pip setuptools wheel tox
        pip install -r ./requirements.txt ;
        pip install flake8 || true ;
        pip install pyflakes || true ;
        pip install pep8 || true ;
    - name: Pre-Clean
      run: make -j1 -f Makefile clean || true ;
    - name: Testing Style
      run: make -j1 -f Makefile test-tox || true ;
    - name: Post-Clean
      run: make -j1 -f Makefile clean || true ;
      if: ${{ always() }}
