name: CI
on: [push]
jobs:
  BUILD:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pre-Clean
      run: make -j1 -f Makefile clean || true ;
    - name: Run Tests
      run: |
        echo Testing Build,
        make -j1 -f Makefile build || true
    - name: Post-Clean
      run: make -j1 -f Makefile purge || true ;

  COVERAGE:
    if: ${{ always() }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    env:
      OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup dependencies
      run: |
        pip install -r ./requirements.txt ;
        pip install coverage>=5.0 || true ;
    - name: Pre-Clean
      run: make -j1 -f Makefile clean || true ;
    - name: Run Tests
      run: make -j1 -f Makefile test ;
    - name: Post-Clean
      run: make -j1 -f Makefile clean || true ;

  COVERAGE:
    needs: [BUILD, MATS]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    env:
      OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        echo Setup dependencies,
        pip install -r ./requirements.txt ;
        pip install coverage>=5.0 ;
    - name: Pre-Clean
      run: make -j1 -f Makefile clean || true ;
    - name: Run Tests
      run: make -j1 -f Makefile test ;
    - run: |
        coverage combine || coverage3 combine || python -m coverage combine ;
        coverage xml || coverage3 xml || python -m coverage xml ;
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        env_vars: OS,PYTHON
        drirectory: ${{ github.workspace }}
        fail_ci_if_error: true
        files: coverage.xml
        flags: unittests
        name: codecov-github-action
        verbose: true
    - name: Post-Clean
      run: make -j1 -f Makefile clean || true ;

  STYLE:
    if: ${{ always() }}
    needs: [BUILD, MATS]
    runs-on: ubuntu-latest

    env:
      PYTHON: '3.9'

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Setup Linters
      run: |
        echo Setup linters,
        pip install -r ./requirements.txt
    - name: Pre-Clean
      run: make -j1 -f Makefile clean || true ;
    - name: Run Tests
      run: |
        echo Testing Style,
        make -j1 -f Makefile test-style || true
    - name: Post-Clean
      run: make -j1 -f Makefile clean || true ;
