name: CI
on: [push]
jobs:
  MATS:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Pre-Clean
      run: make -j1 -f Makefile clean || true ;
    - name: Run Tests
      run: |
        echo Testing M.A.T.s,
        make -j1 -f Makefile test || true
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage1.xml,./coverage2.xml
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true    
    - name: Post-Clean
      run: make -j1 -f Makefile clean || true ;

  STYLE:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pre-Clean
      run: make -j1 -f Makefile clean || true ;
    - name: Run Tests
      run: |
        echo Testing Style,
        make -j1 -f Makefile test-style || true
    - name: Post-Clean
      run: make -j1 -f Makefile clean || true ;

  BUILD:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pre-Clean
      run: make -j1 -f Makefile clean || true ;
    - name: Run Tests
      run: |
        echo Testing Build,
        make -j1 -f Makefile build || true
    - name: Post-Clean
      run: make -j1 -f Makefile purge || true ;
